import { IsInt, IsOptional, Max, Min } from 'class-validator';

export class UploadFileDto {
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(7)
  expiryDays?: number;
}
// TODO: Generated by GitHub Copilot — see docs/ai-usage/us01-copilot-prompts.md (Prompt 2)
