import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { MinioService } from './minio.service';

@Module({
  imports: [ConfigModule],
  providers: [MinioService],
  exports: [MinioService],
})
export class MinioModule {}
// TODO: Generated by GitHub Copilot — see docs/ai-usage/us01-copilot-prompts.md (Prompt 1)
