import { Injectable, Logger, NotFoundException, ForbiddenException, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../prisma/prisma.service';
import { MinioService } from '../minio/minio.service';
import { UploadFileDto } from './dto/upload-file.dto';
import { randomUUID } from 'crypto';
import * as path from 'path';

@Injectable()
export class FilesService {
  private readonly logger = new Logger(FilesService.name);
  private readonly maxFileSize: number;
  private readonly forbiddenExts = ['.exe', '.bat', '.cmd', '.sh', '.ps1'];

  constructor(
    private readonly prisma: PrismaService,
    private readonly minioService: MinioService,
    private readonly config: ConfigService,
  ) {
    this.maxFileSize = this.config.get<number>('MAX_FILE_SIZE_BYTES', 1073741824);
  }

  async uploadFile(userId: string, file: Express.Multer.File, dto?: UploadFileDto) {
    try {
      if (!file) throw new BadRequestException('No file provided');

      if (file.size > this.maxFileSize) {
        throw new BadRequestException('File size exceeds maximum allowed');
      }

      const ext = path.extname(file.originalname).toLowerCase();
      if (this.forbiddenExts.includes(ext)) {
        throw new BadRequestException('File extension is forbidden');
      }

      const key = `${userId}/${randomUUID()}-${file.originalname}`;

      await this.minioService.uploadFile(key, file.buffer, file.mimetype);

      const expiryDays = dto?.expiryDays ?? this.config.get<number>('FILE_EXPIRY_DAYS_DEFAULT', 7);
      const expiresAt = expiryDays ? new Date(Date.now() + expiryDays * 24 * 60 * 60 * 1000) : null;

      const created = await this.prisma.file.create({
        data: {
          userId,
          originalName: file.originalname,
          storagePath: key,
          mimeType: file.mimetype,
          sizeBytes: file.size,
          expiresAt,
        },
      });

      return created;
    } catch (err) {
      this.logger.error('uploadFile failed', err as any);
      throw err;
    }
  }

  async findAllByUser(userId: string) {
    try {
      return this.prisma.file.findMany({
        where: { userId, isDeleted: false },
        orderBy: { createdAt: 'desc' },
      });
    } catch (err) {
      this.logger.error('findAllByUser failed', err as any);
      throw err;
    }
  }

  async findOne(id: string, userId: string) {
    try {
      const file = await this.prisma.file.findUnique({ where: { id } });
      if (!file) throw new NotFoundException('File not found');
      if (file.userId !== userId) throw new ForbiddenException('Access denied');
      if (file.isDeleted) throw new NotFoundException('File not found');
      return file;
    } catch (err) {
      this.logger.error('findOne failed', err as any);
      throw err;
    }
  }

  async remove(id: string, userId: string) {
    try {
      const file = await this.findOne(id, userId);

      await this.minioService.deleteFile(file.storagePath);

      await this.prisma.file.update({ where: { id }, data: { isDeleted: true } });

      // Invalidate download tokens associated with this file
      await this.prisma.downloadToken.updateMany({ where: { fileId: id }, data: { expiresAt: new Date() } });
    } catch (err) {
      this.logger.error('remove failed', err as any);
      throw err;
    }
  }
}
// TODO: Generated by GitHub Copilot — see docs/ai-usage/us01-copilot-prompts.md (Prompt 2)
